# Generated by Django 3.0 on 2020-12-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(choices=[('Clifton Hill', 'Clifton Hill'), ('Forest Hill', 'Forest Hill'), ('Kew', 'Kew'), ('Richmond', 'Richmond')], max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('nname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(choices=[('Working Towards Cert III', 'Working Towards Cert III'), ('Cert III', 'Cert III'), ('Working Towards Diploma', 'Working Towards Diploma'), ('Diploma', 'Diploma'), ('Working Towards Degree', 'Working Towards Degree'), ('Degree', 'Degree'), ('Working Towards Master Degree', 'Working Towards Master Degree'), ('Master Degree', 'Master Degree'), ('Others', 'Others')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
