# Generated by Django 3.0 on 2020-12-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='nname',
            new_name='nick_name',
        ),
    ]
