# Generated by Django 3.0 on 2020-12-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0002_auto_20201222_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(default='06:30', null=True)),
                ('end_time', models.TimeField(default='18:30', null=True)),
            ],
        ),
    ]
