# Generated by Django 3.0 on 2020-12-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0003_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift_start_time', models.TimeField(default='06:30', null=True)),
                ('shift_end_time', models.TimeField(default='18:30', null=True)),
                ('qualification', models.CharField(choices=[('Cert III or above', 'Cert III or above'), ('Diploma or above', 'Diploma or above')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Staff'),
        ),
        migrations.AddField(
            model_name='availability',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift_start_time', models.TimeField(null=True)),
                ('shift_end_time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], max_length=200, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Availability')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Job')),
            ],
        ),
    ]
