# Generated by Django 3.0 on 2020-12-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0004_auto_20201227_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='job',
        ),
    ]
