# Generated by Django 3.0 on 2020-12-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0005_remove_booking_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
