# Generated by Django 3.0 on 2020-12-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0006_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift_start_time', models.TimeField(default='06:30', null=True)),
                ('shift_end_time', models.TimeField(default='18:30', null=True)),
                ('qualification', models.CharField(choices=[('Cert III or above', 'Cert III or above'), ('Diploma or above', 'Diploma or above')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Manager')),
            ],
        ),
    ]
