# Generated by Django 3.0 on 2020-12-27 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casuals', '0008_staff_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Educator',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='staff',
            new_name='educator',
        ),
    ]
