# Generated by Django 3.0 on 2020-12-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0009_auto_20201227_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
