# Generated by Django 3.0 on 2020-12-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0010_educator_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='availability',
        ),
        migrations.AddField(
            model_name='booking',
            name='educator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Educator'),
        ),
    ]
