# Generated by Django 3.0 on 2021-01-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0011_auto_20201231_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casuals.Manager'),
        ),
    ]
