# Generated by Django 3.0 on 2021-01-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0012_booking_centre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='centre',
            new_name='manager',
        ),
    ]
