# Generated by Django 3.0 on 2021-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0013_auto_20210102_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], max_length=200),
        ),
    ]
