# Generated by Django 3.0 on 2021-01-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuals', '0014_auto_20210105_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], max_length=200, null=True),
        ),
    ]
